# Generated by Django 4.2.1 on 2023-05-22 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dvlink.status'),
        ),
    ]
