# Generated by Django 4.2.1 on 2023-05-22 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0003_employee_applications_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='pos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dvlink.position'),
        ),
    ]
