# Generated by Django 4.2.1 on 2023-05-22 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0004_position_employee_pos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['-time_create'], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id', 'pos'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудник'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['id'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должность'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id'], 'verbose_name': 'Статус заявки', 'verbose_name_plural': 'Статус заявки'},
        ),
        migrations.AlterField(
            model_name='applications',
            name='appeal',
            field=models.TextField(blank=True, verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dvlink.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='organization',
            field=models.CharField(max_length=255, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dvlink.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dvlink.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Статус'),
        ),
    ]
