# Generated by Django 4.2.1 on 2023-05-26 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0005_alter_applications_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудник'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pos',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
