# Generated by Django 4.2.1 on 2023-05-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0006_alter_employee_options_remove_employee_pos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='organization',
            new_name='field_organisation_name',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='appeal',
            new_name='field_text_appeal',
        ),
    ]
