# Generated by Django 4.2.1 on 2023-05-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0007_rename_organization_applications_field_organisation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='field_email',
            field=models.CharField(max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='applications',
            name='field_fio',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='applications',
            name='field_number_phone',
            field=models.CharField(max_length=255, null=True, verbose_name='Телефон'),
        ),
    ]
