# Generated by Django 4.2.1 on 2023-05-30 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0009_applications_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dvlink.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='field_email',
            field=models.EmailField(max_length=255, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='field_text_appeal',
            field=models.CharField(max_length=255, verbose_name='Обращение'),
        ),
        migrations.AlterField(
            model_name='applications',
            name='stat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dvlink.status', verbose_name='Статус'),
        ),
    ]
