# Generated by Django 4.2.1 on 2023-06-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0013_delete_user_applications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='field_number_phone',
            field=models.CharField(max_length=18, null=True, verbose_name='Телефон'),
        ),
    ]
