# Generated by Django 4.2.1 on 2023-06-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0017_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organisation_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Организация'),
        ),
    ]
