# Generated by Django 4.2.1 on 2023-06-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0019_profile_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
