# Generated by Django 4.2.1 on 2023-06-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0020_alter_applications_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='user_order_id',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер заявки'),
        ),
    ]
