# Generated by Django 4.2.1 on 2023-06-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvlink', '0021_applications_user_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='user_order_id',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядковый номер заявки'),
        ),
    ]
